### ISSUE TITLE
Slave and master mode can be active simultaneously

### ISSUE THREAD

**Issue by joboet** [supercoder186/XSharedCockpit#2]
The current toggle commands do not check whether the other mode is active. This can lead to both modes being active at the same time, which makes no sense and will lead to strange behaviour.
**Fix:** Control the mode via the state dataref. Add three items in the menu for the three states and add a checkmark to the active one.

If you want, I could make a pull request with the suggested fixes. Great plugin, by the way!

**Comment by supercoder186** [comment]
The slave and master mode cannot be active at the same time. If the plugin is already in a running state, then the other mode cannot start. For example, when the slave starts, it will set "running" to true and therefore if the user tries to start master, it will see that the program is running
