### ISSUE TITLE
Build script for linux

### ISSUE THREAD

**Issue by supercoder186** [supercoder186/XSharedCockpit#7]
The automated build in the cloud is very nice and helpful. However I would also need a build script for linux that creates a build for linux (easy) and for windows (not sure how to do this) - if @CoffeeBlend could help out with this, that would be excellent since I have very little experience with CMake

**Comment by joboet** [comment]
The current action script already does that, it runs on all three platforms. You could, however, change it to upload the individual plugins not only on release, but also on push by removing line 36, 67, 100 of the script (the if-statements), which uploads the plugins as build artefacts under the actions tab.

**Comment by joboet** [comment]
The CMake script should work exactly as the QMake script did, you only have to specify the directories of the SDK (and Boost on Windows). You can specify -G "MingW Makefiles" to build MingW Makefiles on Windows, or any other generator CMake supports. I'm not sure if the build script works with Visual Studio, though.

macOS:
cmake -B build -DXSDK_DIR=/path_to_SDK
cmake --build build
cmake --install --prefix ./dist build

Windows (MingW):
cmake -B build -G "MingW Makefiles" -DXSDK_DIR=/path_to_SDK -DBoost_ROOT=/path_to_Boost
cmake --build build
cmake --install --prefix ./dist build

Linux:
_Same as macOS_

Edit: Clarified instructions, correct commands

**Comment by joboet** [comment]
The last two commits completely break the build. The beauty of CMake is that it can find certain packages for you, commit effdf91 breaks that.

**Comment by supercoder186** [comment]
Okay then, I'll revert the CMakeLists.txt file back to the one in your pull request. Where would I have to place the boost library folder in order to have it detected by CMake, because right now it isn't getting detected

**Comment by joboet** [comment]
On Windows, the CMake detection normally fails, that's why we can set the Boost_ROOT variable to a directory of your choice, for example -DBoost_ROOT=./lib/Boost, and CMake should find it there. On Linux, it looks in the PATH, so you can simply install it via your package manager of choice and it should be found.

**Comment by supercoder186** [comment]
I keep getting this error
`CMake Error at /usr/share/cmake-3.16/Modules/FindBoost.cmake:1636 (file):
  file STRINGS file "/media/user/500GB Ext
  Disk/Programming/X-Plane/XSharedCockpit/<UNSET>/boost/version.hpp" cannot
  be read.`

**Comment by joboet** [comment]
Ah, I found out you have to specify Boost_INCLUDEDIR as well, sorry about that. (e.g. -DBoost_INCLUDEDIR=/path_to_boost/include)

**Comment by supercoder186** [comment]
ahh ok thank you, I'll try the fix tomorrow

**Comment by supercoder186** [comment]
@CoffeeBlend hey there - I'm looking at getting the cmake build working since a _lot_ of people appear to be having problems with dependencies on the qmake version. I'll be using homebrew as a package manager for the wsl system that i use to build for linux, and vcpkg on windows. Hopefully, like this, I can get it building quick & easy on cmake, and upload a version for people to test on the X-Plane forums :)

**Comment by supercoder186** [comment]
Okay, after some work, I have gotten it to build properly with linux in WSL (!!)
To share my experience, for some reason, CMake was able to find Boost when I first opened the linux shell and ran the build,
so like this 
`wsl
./buildplugin.sh`
but it would not work if I tried
`wsl "./buildplugin.sh"` - very strange, no idea why
So instead i just linked the boost include dir directly to what i had in the lib folder
I think that closes this issue, which is excellent :)
